In [3]:
from __future__ import print_function
import torch as t
t.__version__

'1.2.0'

In [5]:
a=t.Tensor(2,3)

In [6]:
a

tensor([[9.2256e+11, 4.5663e-41, 9.2255e+11],
        [4.5663e-41, 9.2254e+11, 4.5663e-41]])

In [8]:
b=t.Tensor([[1,2,3],[4,5,6]]
        )

In [9]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [10]:
b.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [11]:
b_size=b.size()

In [12]:
b_size

torch.Size([2, 3])

In [14]:
b.numel()

6

In [15]:
c=t.Tensor(b_size)

In [16]:
d=t.Tensor((2,3))

In [17]:
c,d

(tensor([[-1.4076e-36,  4.5663e-41, -1.4076e-36],
         [ 4.5663e-41, -1.7492e-37,  4.5663e-41]]), tensor([2., 3.]))

In [18]:
c.shape

torch.Size([2, 3])

In [19]:
t.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [20]:
t.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
t.arange(1,6,2)

tensor([1, 3, 5])

In [22]:
t.linspace(1,10,3)

tensor([ 1.0000,  5.5000, 10.0000])

In [23]:
t.randn(2,3,device=t.device('cpu'))

tensor([[-0.7982,  0.3296,  0.1340],
        [-1.0554,  0.8205,  0.0739]])

In [24]:
t.randperm(5)

tensor([3, 1, 0, 4, 2])

In [25]:
t.eye(2,2,dtype=t.int)

tensor([[1, 0],
        [0, 1]], dtype=torch.int32)

In [26]:
scalar=t.tensor(3.14159)

In [27]:
print('scalar:%s,shape of scalar:%s'%(scalar,scalar.shape))

scalar:tensor(3.1416),shape of scalar:torch.Size([])


In [30]:
vector=t.tensor([2,3])
print('vector:%s,shape of vector:%s'%(vector,vector.shape))


vector:tensor([2, 3]),shape of vector:torch.Size([2])


In [31]:
tensor=t.Tensor(2,3)
tensor.shape





torch.Size([2, 3])

In [34]:
matrix=t.tensor([[0.1,0.2],[2.1,2.2],[4.1,5.3]])
matrix,matrix.shape

(tensor([[0.1000, 0.2000],
         [2.1000, 2.2000],
         [4.1000, 5.3000]]), torch.Size([3, 2]))

In [35]:
t.tensor([[0.1111,0.2222,0.3333333]],dtype=t.float64,device=t.device('cpu'))

tensor([[0.1111, 0.2222, 0.3333]], dtype=torch.float64)

In [39]:
t.tensor([1,2,3]).shape


torch.Size([3])

In [41]:
t.Tensor(3).shape

torch.Size([3])

In [42]:
empty_tensor=t.tensor([])

In [43]:
empty_tensor.shape

torch.Size([0])

# 常用tensor操作

In [44]:
a=t.arange(0,6)

In [45]:
a.view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [46]:
b=a.view(-1,3)

In [47]:
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [50]:
b.unsqueeze(1)
b[:,None].shape

torch.Size([2, 1, 3])

In [51]:
b.unsqueeze(-2)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [52]:
c=b.view(1,1,1,2,3)
c.squeeze(0)

tensor([[[[0, 1, 2],
          [3, 4, 5]]]])

In [53]:
c.squeeze()

tensor([[0, 1, 2],
        [3, 4, 5]])

In [54]:
a


tensor([0, 1, 2, 3, 4, 5])

In [55]:
a[1]=100

In [56]:
b

tensor([[  0, 100,   2],
        [  3,   4,   5]])

In [57]:
b.resize_(1,3)

tensor([[  0, 100,   2]])

In [58]:
b.resize_(3,3)

tensor([[              0,             100,               2],
        [              3,               4,               5],
        [ 94478772086144, 139958017817760,           29295]])

# 索引操作